apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-gihzu4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gihzu4
  namespace: my-nginx-gihzu4
  labels:
    name: nginx-gihzu4
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-gihzu4
  template:
    metadata:
      namespace: my-nginx-gihzu4
      labels:
        name: nginx-gihzu4
    spec:
      containers:
      - name: nginx-gihzu4
        image: nginx
        ports:
        - containerPort: 80

